# vim: ts=4 sw=4 et
imports:
    - 'cloudify.types'
    - 'neutron-network-type.yaml'


blueprint:
    name: 'neutron-network-test'
    topology:
        -
            name: 'neutron_network'
            type: 'neutron_network'
            interfaces:
                    - 'cloudify.interfaces.network_provisioner'
            properties:
                network:
                    name: 'neutron_network_test'

            policies:
                -
                    name: 'start_detection_policy'
                    rules:
                        -
                            type: 'state_equals'
                            properties:
                                service: 'network status'
                                state: 'running'
